version: 2.1

orbs:
  codacy: codacy/base@2.0.1
  codacy_plugins_test: codacy/plugins-test@0.7.1

jobs:
  run_unit_tests:
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          BUNDLE_PATH: vendor/bundle
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: run tests
          command: |
            bundle install --jobs=4 --retry=3
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/unit-test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES
      # collect reports
      - store_test_results:
          path: /tmp/unit-test-results
      - store_artifacts:
          path: /tmp/unit-test-results
          destination: unit-test-results

workflows:
  version: 2
  test_and_publish:
    jobs:
      - codacy/checkout_and_version
      - run_unit_tests:
          requires:
            - codacy/checkout_and_version
      - codacy/shell:
          name: publish_local
          cmd: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          requires:
            - publish_local
      - codacy/shell:
          name: publish_dockerhub
          context: CodacyDocker
          cmd: |
            docker load --input ~/workdir/docker-image.tar
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:latest
            docker push codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME:latest
          requires:
            - run_unit_tests
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish_dockerhub
