version: 2.1

orbs:
  codacy: codacy/base@2.7.0
  codacy_plugins_test: codacy/plugins-test@0.10.2

jobs:
  run_unit_tests:
    docker:
      - image: circleci/ruby:2.7.0
        environment:
          BUNDLE_PATH: vendor/bundle
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: run tests
          command: |
            bundle install --jobs=4 --retry=3
            mkdir -p /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/unit-test-results/rspec.xml \
                              $TEST_FILES
      # collect reports
      - store_test_results:
          path: /tmp/unit-test-results
      - store_artifacts:
          path: /tmp/unit-test-results
          destination: unit-test-results

workflows:
  version: 2
  test_and_publish:
    jobs:
      - codacy/checkout_and_version
      - run_unit_tests:
          requires:
            - codacy/checkout_and_version
      - codacy/shell:
          name: publish_local
          cmd: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - run_unit_tests
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
